name: github-sourcecommit-sync

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Sync up to SourceCommit
        uses: brictoworks/github-sourcecommit-sync-action@master
        with:
          repository_url: ${{ secrets.TEST_REPOSITORY_URL }}
          ssh_private_key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          ssh_key: ${{ secrets.TEST_SSH_KEY }}